version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb  
    network_mode: host