version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - DISPLAY=host.docker.internal:0.0
      - PYTHONUNBUFFERED=1
    network_mode: host  # Required for X11
    ipc: host  # Helps with Qt shared memory issues